### ISSUE TITLE
Some gaps

### ISSUE THREAD

**Issue by Sichara** [DStereo/angular-global#1]
1. add <name>.module.ts for all components with exports property
2. Add SharedModule/CoreModule with exports property
3. Add templates to components intead template string
4. Missing user, login/logout components
5. Redundant directive
6. I think on page "courses" you should use component course-list from SharedModule/CoreModule. This component should include course-item component
7. I'll add more abstract components: Button, CourseList, CourseHeader, CourseActions, CourseDescription,

**Comment by DStereo** [comment]
Created separate components for CoursesList, CourseHead, CourseControls, CourseDescription.
