### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by Sichara** [DStereo/angular-global#2]
1. No console.log on add/edit/delete clicks
2. add sass
3.  I think console.log of search query should be in parent component
4. Missing typing for methods like getDuration. Please add types for methods (including void)
5. Add service for CoursesComponent and use it to get courses list

**Comment by DStereo** [comment]
Fixed 1 and 3 points.

**Comment by DStereo** [comment]
Fixed 2.

**Comment by DStereo** [comment]
Fixed 4.

**Comment by DStereo** [comment]
All done.
